server:
  applicationConnectors:
  - type: http
    port: 8001
  adminConnectors:
  - type: http
    port: 9001


dataSourceFactory:
  # the name of your JDBC driver
  driverClass: com.mysql.jdbc.Driver

 # the JDBC URL
  url: jdbc:mysql://localhost:3306/workflowconnector?autoReconnect=true

  # the username
  user: root

  password:

  # any properties specific to your JDBC driver:
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLDialect  #org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate.hbm2ddl.auto: update

#databaseConfiguration:
#  driverClass: org.hsqldb.jdbc.JDBCDriver
#  url: jdbc:hsqldb:mem:testdb
#  properties:
#    hibernate.dialect : org.hibernate.dialect.HSQLDialect
#    hibernate.show_sql : true
#    hibernate.hbm2ddl.auto : update
#    hibernate.archive.autodetection: class, hbm
